repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        name: check-yaml (workflows)
        files: ^\.github/workflows/.*\.ya?ml$
      - id: check-toml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
        pass_filenames: true
      - id: ruff-lint
        name: ruff lint
        entry: uv run ruff check
        language: system
        types_or: [python, pyi]
        pass_filenames: true
